// Code generated by "go-sumtypes -name Vehicle -type Car,Ship"; DO NOT EDIT.

package testfixture

var _ Vehicle = (*Car)(nil)
var _ Vehicle = (*Ship)(nil)

func (x *Car) Match(v VehicleVisitor)  { v.CaseCar(x) }
func (x *Ship) Match(v VehicleVisitor) { v.CaseShip(x) }

type Vehicle interface {
	Match(VehicleVisitor)
}

type VehicleVisitor interface {
	CaseCar(*Car)
	CaseShip(*Ship)
}

type VehicleVisitorImpl struct {
	CaseCarFunc  func(*Car)
	CaseShipFunc func(*Ship)
}

func (c VehicleVisitorImpl) CaseCar(x *Car) {
	if c.CaseCar == nil {
		return
	}
	c.CaseCar(x)
}
func (c VehicleVisitorImpl) CaseShip(x *Ship) {
	if c.CaseShip == nil {
		return
	}
	c.CaseShip(x)
}
func VehicleMatcher(
	caseCar func(Car *Car),
	caseShip func(Ship *Ship),
) VehicleVisitor {
	return VehicleVisitorImpl{
		CaseCarFunc:  caseCar,
		CaseShipFunc: caseShip,
	}
}
